import Link from "next/link";
import { cookies } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { CaseDetailsForm, CaseMessageComposer, CaseStatusActions } from "@/components/case-workroom-controls";
import { WorkspaceTopbar } from "@/components/workspace-shell";
import { getDatabase } from "@/db/client";
import { getCaseWorkroom } from "@/db/repositories/case-workroom";
import { createOrganizationContextRepository } from "@/db/repositories/organizations";
import { createSessionRepository } from "@/db/repositories/sessions";
import { systemClock } from "@/infrastructure/clock";
import { readSessionCookie, type SessionCookieStore } from "@/infrastructure/session-cookie";
import { resolveWorkspaceContext } from "@/services/organization-context";
import { getCurrentUserContext } from "@/services/session-service";
import { addCaseMessageAction, changeCaseStatusAction, updateCaseDetailsAction } from "./actions";

const transitions = { NEW: ["TRIAGED","CLOSED"], TRIAGED: ["NEW","IN_PROGRESS","CLOSED"], IN_PROGRESS: ["TRIAGED","WAITING_ON_CLIENT","RESOLVED"], WAITING_ON_CLIENT: ["IN_PROGRESS","RESOLVED"], RESOLVED: ["IN_PROGRESS","CLOSED"], CLOSED: ["IN_PROGRESS"] } as const;

export default async function CaseWorkroomPage({ params }: { params: Promise<{ organizationSlug: string; caseId: string }> }) {
  const { organizationSlug, caseId } = await params; const database = getDatabase(); const jar = await cookies(); const store: SessionCookieStore = { get: (name) => jar.get(name), set: () => undefined }; const user = await getCurrentUserContext(createSessionRepository(database), systemClock, readSessionCookie(store)); if (!user) redirect(`/sign-in?returnTo=/${organizationSlug}/cases/${caseId}`); const context = await resolveWorkspaceContext(createOrganizationContextRepository(database), user, organizationSlug); if (!context || context.role === "CLIENT") notFound(); const data = await getCaseWorkroom(database, context.id, caseId); if (!data) notFound(); const { record } = data; const updatedAt = record.updatedAt.toISOString(); const timeline = [...data.messages, ...data.activities].sort((a,b) => a.createdAt.getTime() - b.createdAt.getTime());
  return <main className="clients-page"><WorkspaceTopbar slug={context.slug} active="cases" isDemo={context.isDemo} /><div className="workroom-page"><header className="workroom-heading"><div><Link href={`/${context.slug}/cases`}>← Back to cases</Link><p className="auth-kicker">Case CL-{record.sequence}</p><h1>{record.title}</h1><p>{record.description}</p></div><CaseStatusActions action={changeCaseStatusAction.bind(null, context.slug, caseId)} status={record.status} transitions={[...transitions[record.status]]} updatedAt={updatedAt} /></header><div className="workroom-layout"><aside><section><h2>Case details</h2><CaseDetailsForm action={updateCaseDetailsAction.bind(null, context.slug, caseId)} assigneeId={record.assigneeId ?? ""} categories={data.categories} categoryId={record.categoryId ?? ""} dueAt={record.dueAt ? record.dueAt.toISOString().slice(0,10) : ""} members={data.members} priority={record.priority} updatedAt={updatedAt} /></section><section className="workroom-client"><h2>Client context</h2><dl><div><dt>Client</dt><dd>{record.clientName}</dd></div><div><dt>Requester</dt><dd>{record.requesterName ?? "No requester"}</dd></div><div><dt>Created</dt><dd>{formatDate(record.createdAt)}</dd></div>{record.resolvedAt ? <div><dt>Resolved</dt><dd>{formatDate(record.resolvedAt)}</dd></div> : null}{record.closedAt ? <div><dt>Closed</dt><dd>{formatDate(record.closedAt)}</dd></div> : null}</dl></section></aside><div className="workroom-stream"><CaseMessageComposer action={addCaseMessageAction.bind(null, context.slug, caseId)} updatedAt={updatedAt} /><section className="case-timeline"><header><div><p className="auth-kicker">Audit trail</p><h2>Activity</h2></div><span>{timeline.length} events</span></header>{timeline.length ? <ol>{timeline.map((item) => item.kind === "message" ? <li className={`timeline-message ${item.visibility === "INTERNAL" ? "internal" : "client"}`} key={`message-${item.id}`}><div><strong>{item.visibility === "INTERNAL" ? "Internal note" : "Client reply"}</strong><span>{item.authorName} · {formatDate(item.createdAt)}</span></div><p>{item.body}</p></li> : <li className="timeline-event" key={`activity-${item.id}`}><i aria-hidden="true" /><div><strong>{activityLabel(item.eventType, item.metadata)}</strong><span>{item.actorName ?? "System"} · {formatDate(item.createdAt)}</span></div></li>)}</ol> : <div className="timeline-empty"><strong>No activity yet</strong><p>Updates, messages, and status changes will appear here.</p></div>}</section></div></div></div></main>;
}

function formatDate(value: Date) { return value.toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }); }
function activityLabel(type: string, metadata: Record<string, string | number | boolean | null>) { if (type === "STATUS_CHANGED") return `Status changed from ${label(String(metadata.from))} to ${label(String(metadata.to))}`; if (type === "CASE_UPDATED") return `Case details updated: ${String(metadata.fields).replaceAll(",", ", ")}`; if (type === "MESSAGE_ADDED") return metadata.visibility === "INTERNAL" ? "Internal note recorded" : "Client reply recorded"; if (type === "CASE_CREATED") return "Case created"; return label(type); }
function label(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase()); }
