import { randomUUID } from "node:crypto";
import { eq, inArray } from "drizzle-orm";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createDatabaseConnection, type DatabaseConnection } from "@/db/client";
import { createTeamRepository } from "@/db/repositories/team";
import { cases, clients, memberships, organizations, users } from "@/db/schema";

const url = process.env.TEST_DATABASE_URL; const describeWithDatabase = url ? describe : describe.skip;
describeWithDatabase("team member workspace with PostgreSQL", () => {
  let connection!: DatabaseConnection; const organizationIds: string[] = []; const userIds: string[] = [];
  beforeAll(() => { connection = createDatabaseConnection(url!); }); afterAll(async () => { if (organizationIds.length) await connection.database.delete(organizations).where(inArray(organizations.id, organizationIds)); if (userIds.length) await connection.database.delete(users).where(inArray(users.id, userIds)); await connection.close(); });
  async function fixture() { const suffix = randomUUID(); const [organization] = await connection.database.insert(organizations).values({ name: "Team tenant", slug: `team-${suffix}` }).returning(); const [other] = await connection.database.insert(organizations).values({ name: "Other tenant", slug: `other-team-${suffix}` }).returning(); const [owner] = await connection.database.insert(users).values({ name: "Protected Owner", email: `owner-${suffix}@example.test`, passwordHash: "test" }).returning(); const [member] = await connection.database.insert(users).values({ name: "Casey Brooks", email: `member-${suffix}@example.test`, passwordHash: "test" }).returning(); if (!organization || !other || !owner || !member) throw new Error("Fixture failed."); organizationIds.push(organization.id, other.id); userIds.push(owner.id, member.id); await connection.database.insert(memberships).values([{ organizationId: organization.id, userId: owner.id, role: "OWNER" }, { organizationId: organization.id, userId: member.id, role: "MEMBER", title: "Coordinator" }]); const [client] = await connection.database.insert(clients).values({ organizationId: organization.id, name: "Client" }).returning(); if (!client) throw new Error("Client fixture failed."); await connection.database.insert(cases).values({ organizationId: organization.id, sequence: 1001, clientId: client.id, assigneeId: member.id, createdById: owner.id, title: "Assigned request", description: "Assigned workload context.", priority: "HIGH", dueAt: new Date("2020-01-01") }); return { organization, other, owner, member }; }
  it("returns tenant-scoped profile and real workload", async () => { const { organization, other, member } = await fixture(); const repository = createTeamRepository(connection.database); const profile = await repository.getMember(organization.id, member.id, new Date()); expect(profile).toMatchObject({ title: "Coordinator", assignedCases: 1, activeCases: 1, overdueCases: 1 }); expect(profile?.recentCases).toHaveLength(1); expect(await repository.getMember(other.id, member.id, new Date())).toBeNull(); });
  it("updates profile atomically while protecting the owner", async () => { const { organization, owner, member } = await fixture(); const repository = createTeamRepository(connection.database); expect(await repository.updateProfile(organization.id, member.id, { name: "Casey Morgan", title: "Operations lead", role: "ADMIN" })).toBe(true); const [updatedUser] = await connection.database.select().from(users).where(eq(users.id, member.id)); const [updatedMembership] = await connection.database.select().from(memberships).where(eq(memberships.userId, member.id)); expect(updatedUser?.name).toBe("Casey Morgan"); expect(updatedMembership).toMatchObject({ title: "Operations lead", role: "ADMIN" }); expect(await repository.updateProfile(organization.id, owner.id, { name: "Changed Owner", role: "MEMBER" })).toBe(false); });
});
