import Link from "next/link";
import { cookies } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { WorkspaceTopbar } from "@/components/workspace-shell";
import { getDatabase } from "@/db/client";
import { getCaseIntakeOptions } from "@/db/repositories/case-intake";
import { listCaseQueue } from "@/db/repositories/case-queue";
import { createOrganizationContextRepository } from "@/db/repositories/organizations";
import { createSessionRepository } from "@/db/repositories/sessions";
import { parseCaseQueueSearchParams, type CaseQueueSearchParams } from "@/domain/case-queue";
import { systemClock } from "@/infrastructure/clock";
import { readSessionCookie, type SessionCookieStore } from "@/infrastructure/session-cookie";
import { resolveWorkspaceContext } from "@/services/organization-context";
import { getCurrentUserContext } from "@/services/session-service";

export default async function CasesPage({ params, searchParams }: { params: Promise<{ organizationSlug: string }>; searchParams: Promise<CaseQueueSearchParams> }) {
  const { organizationSlug } = await params; const database = getDatabase(); const jar = await cookies(); const store: SessionCookieStore = { get: (name) => jar.get(name), set: () => undefined };
  const user = await getCurrentUserContext(createSessionRepository(database), systemClock, readSessionCookie(store)); if (!user) redirect(`/sign-in?returnTo=/${organizationSlug}/cases`);
  const context = await resolveWorkspaceContext(createOrganizationContextRepository(database), user, organizationSlug); if (!context) notFound();
  const query = parseCaseQueueSearchParams(await searchParams); const [page, options] = await Promise.all([listCaseQueue(database, context.id, query, systemClock.now()), getCaseIntakeOptions(database, context.id)]); const hasFilters = Boolean(query.search || query.status || query.priority || query.assigneeId || query.clientId || query.overdue);
  return <main className="clients-page"><WorkspaceTopbar slug={context.slug} active="cases" isDemo={context.isDemo} /><div className="clients-content"><section className="clients-heading"><div><p className="auth-kicker">Operational queue</p><h1>Cases</h1><p>Find the client work that needs ownership, a reply, or a decision.</p></div>{context.role !== "CLIENT" ? <Link className="client-primary-action" href={`/${context.slug}/cases/new`}>New case</Link> : null}</section>
    <form className="case-queue-filters"><label>Search<input defaultValue={query.search} name="search" placeholder="Title or case number" type="search" /></label><label>Status<select defaultValue={query.status ?? ""} name="status"><option value="">All statuses</option>{["NEW","TRIAGED","IN_PROGRESS","WAITING_ON_CLIENT","RESOLVED","CLOSED"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>Priority<select defaultValue={query.priority ?? ""} name="priority"><option value="">All priorities</option>{["LOW","NORMAL","HIGH","URGENT"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>Assignee<select defaultValue={query.assigneeId ?? ""} name="assigneeId"><option value="">Anyone</option><option value="unassigned">Unassigned</option>{options.members.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Client<select defaultValue={query.clientId ?? ""} name="clientId"><option value="">All clients</option>{options.clients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="overdue-check"><input defaultChecked={query.overdue} name="overdue" type="checkbox" value="true" /> Overdue only</label><input name="view" type="hidden" value={query.view} /><button type="submit">Apply</button>{hasFilters ? <Link href={`/${context.slug}/cases?view=${query.view}`}>Clear</Link> : null}</form>
    <div className="queue-view-switch"><span>{page.items.length} shown</span><nav aria-label="Queue view"><Link aria-current={query.view === "list" ? "page" : undefined} href={queryHref(query, { view: "list", cursor: undefined })}>List</Link><Link aria-current={query.view === "board" ? "page" : undefined} href={queryHref(query, { view: "board", cursor: undefined })}>Board</Link></nav></div>
    {page.items.length ? query.view === "board" ? <Board items={page.items} /> : <CaseRows items={page.items} now={systemClock.now()} /> : <div className="clients-empty"><h2>{hasFilters ? "No cases match these filters" : "No cases yet"}</h2><p>{hasFilters ? "Clear or change the filters to return to the active queue." : "Create the first case to connect client work, ownership, and deadlines."}</p>{hasFilters ? <Link href={`/${context.slug}/cases`}>Clear filters</Link> : context.role !== "CLIENT" ? <Link href={`/${context.slug}/cases/new`}>Create first case</Link> : null}</div>}
    {page.nextCursor ? <nav className="client-pagination" aria-label="Case pages"><Link href={queryHref(query, { cursor: page.nextCursor })}>Next page</Link></nav> : null}
  </div></main>;
}

type Item = Awaited<ReturnType<typeof listCaseQueue>>["items"][number];
function CaseRows({ items, now }: { items: Item[]; now: Date }) { return <section className="case-queue-list">{items.map((item) => <Link className="case-queue-row navigable-row" href={`cases/${item.id}`} key={item.id}><div><strong>CL-{item.sequence} · {item.title}</strong><p>{item.clientName}</p></div><span className={`queue-status status-${item.status.toLowerCase().replaceAll("_", "-")}`}>{label(item.status)}</span><span className={item.priority === "URGENT" ? "queue-urgent" : ""}>{label(item.priority)}</span><span>{item.assigneeName ?? "Unassigned"}</span><time className={item.dueAt && item.dueAt < now && !["RESOLVED","CLOSED"].includes(item.status) ? "due-overdue" : ""}>{item.dueAt ? item.dueAt.toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "No due date"}</time></Link>)}</section>; }
function Board({ items }: { items: Item[] }) { return <section className="case-board">{["NEW","TRIAGED","IN_PROGRESS","WAITING_ON_CLIENT","RESOLVED","CLOSED"].map((status) => <div key={status}><header><h2>{label(status)}</h2><span>{items.filter((item) => item.status === status).length}</span></header>{items.filter((item) => item.status === status).map((item) => <Link className="case-board-card navigable-row" href={`cases/${item.id}`} key={item.id}><strong>CL-{item.sequence} · {item.title}</strong><p>{item.clientName}</p><span>{item.assigneeName ?? "Unassigned"}</span></Link>)}</div>)}</section>; }
function label(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase()); }
function queryHref(query: ReturnType<typeof parseCaseQueueSearchParams>, overrides: Record<string, string | undefined>) { const params = new URLSearchParams(); for (const [key, value] of Object.entries({ ...query, ...overrides })) if (value !== undefined && value !== false && value !== "" && key !== "limit") params.set(key, String(value)); return `?${params.toString()}`; }
