import { cookies } from "next/headers";
import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { PortalReplyForm } from "@/components/portal-reply-form";
import { getDatabase } from "@/db/client";
import { getPortalCase, resolvePortalIdentity } from "@/db/repositories/portal";
import { createSessionRepository } from "@/db/repositories/sessions";
import { clientStatus, nextAction } from "@/domain/portal";
import { systemClock } from "@/infrastructure/clock";
import { readSessionCookie, type SessionCookieStore } from "@/infrastructure/session-cookie";
import { getCurrentUserContext } from "@/services/session-service";
import { addPortalReplyAction } from "../actions";
export default async function PortalRequestPage({params}:{params:Promise<{organizationSlug:string;caseId:string}>}) { const {organizationSlug,caseId}=await params; const db=getDatabase(); const jar=await cookies(); const store:SessionCookieStore={get:(name)=>jar.get(name),set:()=>undefined}; const user=await getCurrentUserContext(createSessionRepository(db),systemClock,readSessionCookie(store)); if(!user) redirect(`/sign-in?returnTo=/portal/${organizationSlug}/requests/${caseId}`); const identity=await resolvePortalIdentity(db,user.userId,organizationSlug); if(!identity) notFound(); const data=await getPortalCase(db,identity,caseId); if(!data) notFound(); const status=clientStatus(data.record.status); return <main className="portal-page"><header className="portal-header"><Link href={`/portal/${organizationSlug}/requests`} className="portal-brand"><i aria-hidden="true"><b/><b/><b/></i>CaseLane</Link><div><span>{identity.clientName}</span><strong>{identity.contactName}</strong></div></header><div className="portal-case"><Link className="portal-back" href={`/portal/${organizationSlug}/requests`}>Back to requests</Link><header><div><span className="portal-case-number">CL-{data.record.sequence}</span><h1>{data.record.title}</h1><p>{data.record.description}</p></div><aside><span>{status.label}</span><strong>{nextAction(data.record.status)}</strong><p>{status.detail}</p></aside></header><section className="portal-conversation"><div><p className="portal-kicker">Conversation</p><h2>Updates with the team</h2></div>{data.messages.length?<ol>{data.messages.map(message=><li className={message.isClientAuthor?"from-client":"from-team"} key={message.id}><div><strong>{message.isClientAuthor?"You":message.authorName}</strong><time dateTime={message.createdAt.toISOString()}>{message.createdAt.toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time></div><p>{message.body}</p></li>)}</ol>:<div className="portal-conversation-empty"><strong>No conversation yet</strong><p>The team’s client-visible updates will appear here.</p></div>}<PortalReplyForm action={addPortalReplyAction.bind(null,organizationSlug,caseId)}/></section></div></main> }
